name: Build My firmware

permissions:
  contents: read

on:
  push:
    branches: [atremblay]
  workflow_dispatch:

concurrency: ci_build-${{ github.event.inputs.branch || github.ref_name }}

jobs:
  ci_build:
    name: "CI Build"
    runs-on: ubuntu-latest
    timeout-minutes: 1380

    strategy:
      fail-fast: false
      matrix:
        keymap: [default]

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Run `qmk compile` (keymap ${{ matrix.keymap }})
      run: |
        export NCPUS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
        qmk compile -j $NCPUS -kb keebio/bfo9000/elite-pi -km ${{ matrix.keymap }} -e DUMP_CI_METADATA=yes || touch .failed
        # Exit with failure if the compilation stage failed
        [ ! -f .failed ] || exit 1

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: artifacts-${{ matrix.keymap }}
        if-no-files-found: ignore
        path: |
          *.bin
          *.hex
          *.uf2
          .build/failed.*
